version: '3.7'
services:
  honeycombot:
    image: honeycombot
    networks:
    - jaeger-example
    command: ["--debug", "-k", "YOUR_WRITEKEY", "-d", "examples.jaeger-ot-test"]
  hotrod:
    image: hotrod
    ports: 
    - "8080:8080"
    command: ["all"]
    environment:
    - JAEGER_REPORTER_LOG_SPANS=1
    networks:
    - jaeger-example
    depends_on:
    - honeycombot

networks:
  jaeger-example:
